### ISSUE TITLE
improved use of S4

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#10]
See recently updated https://adv-r.hadley.nz/s4:

- [ ] use constructors instead of `new()`:

    > It’s also possible to create an instance using `new()` and the name of the class. This is not recommended because it introduces some ambiguity. What happens if there are two packages that both define the `Person` class?

- [ ] don't use `{` in generics:

    > Note that it is bad practice to use `{` in the generic function. This triggers a special case that is more expensive, and generally best avoided.

- [ ] use of `setOldClass()`:

    >  If you’re trying to build an S4 class on top of a S3 class provided by a package, it is better to request that the package maintainer add this call to the package, rather than running it yourself.

**Comment by eliotmcintire** [comment]
These 3 are either 1) in place 2) irrelevant (no discernible effect of the {} in a generic), or 3) we use.
