### ISSUE TITLE
[ fastMask ] Doesn't work with raster stack or brick [ enhancement ] [ low priority ]

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/reproducible#102]

**Comment by tati-micheletti** [comment]
Will add a reprex asap

**Comment by eliotmcintire** [comment]
Any chance of having a reprex?

**Comment by tati-micheletti** [comment]
library("raster")
ras1 <- raster()

sa <- SpaDES.tools::randomPolygon(x = matrix(data = c(0, 0), ncol = 2), area = 10^14)
saReproj <- reproducible::projectInputs(x = sa, targetCRS = raster::crs(ras1))

preStack <- reproducible::preProcess(url = "https://github.com/tati-micheletti/host/raw/master/data/grdRasterStack.zip",
                                       destinationPath = tempdir())
# Stack
testStack1 <- reproducible::fastMask(x = raster::stack(preStack$targetFilePath), y = sa)

# Only one layer
testStack2 <- reproducible::fastMask(x = raster::raster(preStack$targetFilePath), y = sa)

# ++++++++
preStackTif <- reproducible::preProcess(url = "https://github.com/tati-micheletti/host/raw/master/data/stackTestTif.zip",
                                     destinationPath = tempdir())
# Stack
testStack3 <- reproducible::fastMask(x = raster::stack(preStackTif$targetFilePath), y = sa)

# Only one layer
testStack4 <- reproducible::fastMask(x = raster::raster(preStackTif$targetFilePath), y = sa)

**Comment by tati-micheletti** [comment]
My suggestion:
Identify if `fun = raster::stack`, if so, `lapply` `fastMask` through the layers, and then `stack` these back again before returning. It should be quick to do. I can eventually get to it this week, depending on free time.

**Comment by eliotmcintire** [comment]
These work for me using current version of `reproducible`. I have changed messaging so that it is a little more precise. 392dba9f3f7187ab36d621b25f8ed2264fe52b05. If this issue is more about creating the sf/gdal methods for `RasterStack`, then this needs a differently named issue.
