### ISSUE TITLE
Cache is changing function's arguments

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/reproducible#109]
```r
A <- c(1, 2, 3, 4, 5, 6)
B <- 2*A + c(0.2, 0.4, -0.3, 0.4, 0.9, -0.5)
C <- c("G1", "G1", "G2", "G2", "G3", "G3")

a <- data.frame(A = A, B = B, C = C)
mod <- lm(formula = A ~ B, data = a)
modCache <- reproducible::Cache(lm, formula = A ~ B, data = a, cacheRepo = tempdir()) 
modCache$call == mod$call ## FALSE
```

```r
> modCache$call
FUN(formula = ..1, data = ..2)
> mod$call
lm(formula = A ~ B, data = a)
```

**Comment by eliotmcintire** [comment]
I am not sure of the consequences of that... Those "..1" etc mean that they are placeholders for the actual arguments. Is it changing the model result? Does it affect anything other than the "call" element of the model object?

**Comment by eliotmcintire** [comment]
```
modNames <- names(mod)
names(modNames) <- modNames
> lapply(modNames, function(x) all.equal(mod[[x]], modCache[[x]]))
$coefficients
[1] TRUE

$residuals
[1] TRUE

$effects
[1] TRUE

$rank
[1] TRUE

$fitted.values
[1] TRUE

$assign
[1] TRUE

$qr
[1] TRUE

$df.residual
[1] TRUE

$xlevels
[1] TRUE

$call
[1] "target, current do not match when deparsed"

$terms
[1] TRUE

$model
[1] TRUE
```

**Comment by tati-micheletti** [comment]
I see. My biggest problem with this is that `Cache` is not tagging the real function, but the placeholder, making it pretty hard to clear cache, and also might trigger a new run if the placeholder for some reason is a different number on the second run.

**Comment by eliotmcintire** [comment]
That is a tag problem. It is not a digest issue. The digest doesn't digest the ..2. It digests the objects. So that is not a problem. We can try to improve the automated userTag procedure. In the short term, just add userTag values. I think it is a good idea to use userTags for many reasons.

**Comment by tati-micheletti** [comment]
should I close the issue?

**Comment by eliotmcintire** [comment]
Yes
