### ISSUE TITLE
projectInputs should check if RasterStack has a data slot

### ISSUE THREAD

**Issue by ygc2l** [PredictiveEcology/reproducible#111]
Getting

```
Error in paste0(x@data@names, "a_reproj.tif") : no slot of name "data" for this object of class "RasterStack"
```

Relevant lines from the traceback:
```
paste0(x@data@names, "a_reproj.tif")
file.path(tmpRasPath, paste0(x@data@names, "a_reproj.tif"))
projectInputs.Raster
```

**Comment by achubaty** [comment]
@CeresBarros did #112 deal with this?
@ygc2l can you please test to see if this is still an issue?

**Comment by CeresBarros** [comment]
It should have... I'm pretty sure I encountered this behaviour while coding for #112 and dealt with it. @ygc2l let me know if not...

**Comment by ygc2l** [comment]
Considered this as fixed.
