### ISSUE TITLE
.robustDigest(env) that contains a `lme4` generated object corrupts the original `lme4` object

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/reproducible#115]
This does not happen to `stats::lm`.

### Reprex on Cache + env + glmer problem
env <- new.env()
dt <- data.frame(a = c(1, 5, 10), 
                 b = c(2, 3, 7), 
                 re = c(1, 1, 3))
modGlmer <- list(MOD1 = lme4::glmer(formula = a ~ b + (1|re), data = dt, family = "poisson"))
modLmer <- list(MOD2 = lme4::lmer(formula = a ~ b + (1|re), data = dt))
modLm <- list(MOD3 = stats::lm(formula = a ~ b, data = dt))

assign(x = "modGlmer", 
       value = modGlmer,
       envir = env)
assign(x = "modLmer", 
       value = modLmer,
       envir = env)
assign(x = "modLm", 
       value = modLm,
       envir = env)

tryCatch(print(modGlmer), error = function(e) 
  message("Original object `modGlmer` was modified by reproducible:::.robustDigest and returns error"))
tryCatch(print(modLmer), error = function(e) 
  message("Original object `modLmer` was modified by reproducible:::.robustDigest and returns error"))
tryCatch(print(modLm), error = function(e) 
  message("Original object `modLm` was modified by reproducible:::.robustDigest and returns error"))

reproducible:::.robustDigest(env)

tryCatch(print(modGlmer), error = function(e) 
  message("Original object `modGlmer` was modified by reproducible:::.robustDigest and returns error"))
tryCatch(print(modLmer), error = function(e) 
  message("Original object `modLmer` was modified by reproducible:::.robustDigest and returns error"))
tryCatch(print(modLm), error = function(e) 
  message("Original object `modLm` was modified by reproducible:::.robustDigest and returns error"))

**Comment by achubaty** [comment]
@tati-micheletti can you please confirm that Eliot's fix solves the problem? thanks.
