### ISSUE TITLE
Changes in googledrive v1.0.0

### ISSUE THREAD

**Issue by jennybc** [PredictiveEcology/reproducible#119]
I will release googledrive v1.0.0 soon.

There are breaking changes to auth that I believe affect this package.

reproducible still passes `R CMD check`, at least running "as CRAN", so there is no obstacle for googledrive, in terms of reverse dependencies. But I think you will notice the changes in normal usage of the reproducible package.

The googledrive changes are described in NEWS.md:

https://googledrive.tidyverse.org/news/index.html

There will also be a blog post about the googledrive release and the gargle package, in general.

**Comment by achubaty** [comment]
Thanks for the head's up @jennybc.

**Comment by achubaty** [comment]
fixed and merged.

thank you @jennybc for advanced notice and for maintaining detailed release notes and package vignettes.
