### ISSUE TITLE
prepInputs: No masking occurs if `maskWithRTM = TRUE` and `rasterToMatch = NULL`

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/reproducible#123]
I just noticed that when calling `prepInputs` to prepare a RasterLayer, if we supply a `studyArea`, `maskWithRTM = TRUE` and `rasterToMatch = NULL`, the raster is cropped to the extent of `studyArea`, but not masked. However, if we set `maskWithRTM = FALSE`, then masking occurs.
I guess this is related to issue #30, as the documentation for `maskInputs` suggests that `studyArea` would be used to mask in the absence of `rasterToMatch`, whatever the value of `maskWithRTM`:
```
studyArea	SpatialPolygons* object used for masking and possibly cropping if no 
                        rasterToMatch is provided. If not in same CRS, then it will be spTransformed to 
                        CRS of x before masking. Currently, this function will not reproject the x. Optional 
                        in postProcess.
```

**Comment by eliotmcintire** [comment]
No longer relevant
