### ISSUE TITLE
remove archivist dependency

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#126]
currently using the following for `Cache`-ing:

```
importFrom(archivist,addTagsRepo)
importFrom(archivist,createLocalRepo)
importFrom(archivist,loadFromLocalRepo)
importFrom(archivist,rmFromLocalRepo)
importFrom(archivist,saveToLocalRepo)
importFrom(archivist,searchInLocalRepo)
importFrom(archivist,showLocalRepo)
importFrom(archivist,splitTagsLocal)
```

We want to move away from using `archivist` in favour of `DBI` directly so that we can make better use of other database backends, namely `postgresql`.

1. Start by rewriting pieces based on <https://db.rstudio.com/dbi/>;
2. Will need directory setup for the raster files (and the sqlite db);
3. Build interface for accessing db credentials from env vars or config files;
4. Build quick-start tools for installing/configuring other db backends and creating databases.

Other considerations?

**Comment by achubaty** [comment]
see also https://journal.r-project.org/archive/2018/RJ-2018-025/index.html

**Comment by eliotmcintire** [comment]
Done in `DBI` branch
