### ISSUE TITLE
document behaviour for prepProcess/prepInputs(..., fun = NULL) and change "load" message

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/reproducible#135]
When using the `fun` argument as `NULL`, `preProcess` doesn't load the object, but still prints the message `Loading object into R`.
This (very useful!) behaviour should be added to the documentation and the message should be changed accordingly.

**Comment by eliotmcintire** [comment]
Fixed in 1ef4928fd41ba3a8e329f365d087fb3704776163
