### ISSUE TITLE
make first part of `.prepareFilebackedRaster` a separate function

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/reproducible#143]
It may be useful to break `.prepareFilebackedRaster` into two parts , one which does all the checking for the object being file-backed and the presence of the actual file (this would be a function called by `.prepareFileBackedRasters`), and the second part with saving the raster backup file and so on.

Having this first part wrapped in a separate function may be useful so that other functions like `postProcess` and company, which often fail due to this issue, can quickly detect if the raster object is file-backed and its file is accessible.

**Comment by eliotmcintire** [comment]
This is no longer relevant.
