### ISSUE TITLE
use of \tabular produces long non-wrapping lines in PDF manual

### ISSUE THREAD

**Issue by yvkschaefer** [PredictiveEcology/reproducible#144]
On page four of https://cran.r-project.org/web/packages/reproducible/reproducible.pdf, midway down the page under the header **Main Tools**, there is a part under _Function_ that cuts off on the side, on Chrome/Firefox, at regular zoom level.

The full text, I see from copy/paste, says 
```
Cache A robust wrapper for any function, including those with environments, disk-backed storage (currently on Raster) class), operating-system independent, whose first time called will execute the function, 2nd time will compare the inputs to a an SQLite database of entries, and recover the first result if inputs are identical. If options("reproducible.useMemoise" = TRUE), the third time will be very fast as it will recover the answer from RAM
prepInputs A function to download, or load objects, and possible post process them. The main advantage to using this over more direct routes is that it will automatically build checksums tables, use Cache internally where helpful, and possibly run a variety of post processing actions. This means this function can also itself be cached for even more speed. This allows all project data to be stored in custom cloud locations or in their original online data repositories, without altering code between the first, second, third etc. times the code is run.
Require
```

But I see something more like:

![Screen Shot 2020-05-08 at 6 06 47 PM](https://user-images.githubusercontent.com/19944050/81458259-bc43db00-9156-11ea-87db-c027c54a6082.png)

It's possible to get the information from the copy/paste, but perhaps it's an easy fix for the team. Full disclosure I didn't check all the other pages yet, but maybe it's possible the same problem arises later in the documentation as well. Thanks for your time and the contribution, I look forward to implementing the use of this package.

**Comment by achubaty** [comment]
`\tabular` still being used in a few places. should use e.g., `\describe` instead to avoid non-breaking/non-wrapping lines in PDF manual.
