### ISSUE TITLE
Problems with unzipping for files > 4GB

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/reproducible#145]
We are having problems with the unzipping again. For some reason the system call for unzipping is not being triggered with this call:

```r
 forestHarvestMask <- prepInputs(url = "https://opendata.nfis.org/downloads/forest_change/CA_forest_harvest_mask_year_1985_2015.zip",
                                 targetFile = "CA_harvest_year_1985_2015.tif",
                                 destinationPath = tempdir(),
                                 fun = "raster::raster",
                                 userTags = c("objectName:forestHarvestMask", "goal:posthocGIS"))
Running preProcess
Preparing: CA_harvest_year_1985_2015.tif
Checking local files...
Finished checking local files.
  Skipping download: CA_harvest_year_1985_2015.tif already present
Loading object into R
Error in .local(.Object, ...) : 
  TIFFReadDirectory:Failed to read directory at offset 30446382458
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.
```

The object it extracted shows this:
![image](https://user-images.githubusercontent.com/33500569/82381166-946a3800-99de-11ea-8db2-d0ccea77afbc.png)

While in Windows:
![image](https://user-images.githubusercontent.com/33500569/82381192-9cc27300-99de-11ea-8434-d7c4e067a39b.png)

**Comment by achubaty** [comment]
Updated your example above to make a reprex. I confirm it's failing for me too.

from `?unzip`:
> It does have some support for `bzip2` compression and > 2GB zip files (but not >= 4GB files pre-compression contained in a zip file: like many builds of `unzip` it may truncate these, in R's case with a warning if possible).

so it does look like the system version isn't being called.

**Comment by tati-micheletti** [comment]
Manually extracting seemed to have worked fine. This file probably did not trigger the system call because it didn't error with unzip call from R (which is what triggers the system call). Maybe a quick patch would be to add an argument to preProcess to allow the user to decide for a system unzip of unzip if they believe the file is > 4GB.

**Comment by achubaty** [comment]
or simply to check the file size
