### ISSUE TITLE
reproducible should not call `usethis::use_lifecycle()`

### ISSUE THREAD

**Issue by lionel-** [PredictiveEcology/reproducible#147]
This is creating side effects on the machines of people building your package, see https://github.com/r-lib/lifecycle/issues/52

The usethis package is only for interactive use at the console, a package itself should never call it. For this reason it should not be in your `Imports:` field either.

**Comment by achubaty** [comment]
This has been removed in https://github.com/PredictiveEcology/reproducible/commit/728145cc8dd436a6a11965b999e5a443923a8976 and will make its way to CRAN in a future release.
