### ISSUE TITLE
Installation fails due to unavailable dependency

### ISSUE THREAD

**Issue by ellnyg** [PredictiveEcology/reproducible#150]
The package `‘Require’` has been removed from CRAN (https://cran.r-project.org/web/packages/Require/index.html). I get the following error when attempting to download `repoducible`:

> > install.packages("reproducible")

> Package required but not available: ‘Require’
> 
> Warning in install.packages :
>   dependency ‘Require’ is not available
> 
>   There is a binary version available but the source version is later:
>              binary source needs_compilation
> reproducible  1.1.1  1.2.0             FALSE
> 
> installing the source package ‘reproducible’
> 
> trying URL 'https://cran.rstudio.com/src/contrib/reproducible_1.2.0.tar.gz'
> Content type 'application/x-gzip' length 284109 bytes (277 KB)
> downloaded 277 KB
> 
> ERROR: dependency 'Require' is not available for package 'reproducible'
> * removing 'C:/Users/ellnyg/rpakker/reproducible'
> Warning in install.packages :
>   installation of package ‘reproducible’ had non-zero exit status

**Comment by achubaty** [comment]
Thanks, an update to CRAN is forthcoming. In the mean time, you can work around this by installing from GitHub:

```
devtools::install_github('PredictiveEcology/Require')
devtools::install_github('PredictiveEcology/reproducible')
```

**Comment by achubaty** [comment]
`Require` v 0.7.0 is back on CRAN.
