### ISSUE TITLE
Compatibility with magrittr 2.0

### ISSUE THREAD

**Issue by lionel-** [PredictiveEcology/reproducible#169]
I see a failure in the magrittr revdep checks because `reproducible` is plucking into magrittr internals in `%C%`. The failure is caused by internal changes in magrittr 2.0.

We're about to release magrittr to CRAN and this will cause `reproducible` to fail their CRAN checks. Unfortunately this didn't show up in our revdepchecks from two months ago, sorry for the late heads up.

**Comment by eliotmcintire** [comment]
Thank you. Will attempt to resolve quickly.

**Comment by eliotmcintire** [comment]
Have pushed a work around to our `development` branch with #170 . It passes all tests now. Will get it to CRAN soon. Thanks @lionel- . Having said that, it looks like it will be difficult to achieve the same caching behaviour now that the magrittr code is compiled. i.e., we need to digest (hash) all the arguments and the functions, without evaluating any of the function calls. The only solution I have come up with so far is to use revive about 10 functions from the legacy code from magrittr <2.0. This would only affect the `%C%` operator. Any `%>%` operators would be using the magrittr 2.0 compiled code. Pushing this to a new issue.

**Comment by lionel-** [comment]
I guess you will have the same issue with the base pipe to be included in 4.1. I agree that if caching or some other special mechanism is needed for your API, using a custom operator is best.

**Comment by lionel-** [comment]
Thanks for the quick fix!
