### ISSUE TITLE
cropReprojMaskWGDAL fails with cryptic error when 'filename2 = NULL'

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#173]
`postProcess` etc. that calls `cropReprojMaskWGDAL` will fail when `flename2 = NULL` with the following error:

```r
ERROR: NA/NaN argument
ERROR: lfn[f]:2
Error in lfn[f]:2 : NA/NaN argument
```
A user may not realize that `gdalwarp` requires a file to work with, and it's not obvious (without doing a `traceback`) why the postProcess call fails in this instance.

**Proposed solution:**
`cropReprojMaskWGDAL` should check for valid filename early, and fail with a meaningful message telling the user to pass valid `filename2`, or to set `options(reproducible.useGDAL = FALSE)`.

**Comment by eliotmcintire** [comment]
No longer relevant
