### ISSUE TITLE
GDAL not setup properly on Mac & Windows in GitHub Actions

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/reproducible#176]
All systems seem to be passing except Mac. May be transient... @achubaty is this something you can look into?

**Comment by achubaty** [comment]
taking a quick look, I don't see it installing suggested packages, of which `rgdal` is one. not sure if the behaviour changed -- i'll take a closer look

**Comment by eliotmcintire** [comment]
I have skipped the automated tests on Mac and Windows that require GDAL _if they are not installed_. This means that the GA doesn't _need_ to have GDAL installed for the tests to pass now. @achubaty if you don't have time to address this, I am happy close this issue (though of course, it would be better to have the GDAL working on GA-Windows and Mac).

**Comment by achubaty** [comment]
I'm not sure what happened to change the behaviour -- those OSes both install binary R packages, and the precompiled `rgdal` used to ship with GDAL. Apparently not now? It should be straightforward to install the neccesary system dependencies, on macOS at least, but I will need to dig a bit deeper to sort things out on Windows.

Presumably this is affecting our other packages?

**Comment by eliotmcintire** [comment]
Not sure if the lack of GDAL will affect other packages. Normally, all our code is testing whether GDAL is installed before trying ti use it. In the case of `reproducible`, we are explicitly testing GDAL functionality. So, when GDAL is not properly installed, then those tests fail.

**Comment by eliotmcintire** [comment]
@achubaty It seems like the Coverage run of GitHub Actions is also not using `gdal` ... can you set that up so it is using `gdal`? It is showing super low coverage values (65%) and I just added a bunch of tests that should have run if gdal was installed. They didn't get run.
