### ISSUE TITLE
Failures with RSQLite 2.2.2

### ISSUE THREAD

**Issue by krlmlr** [PredictiveEcology/reproducible#185]
RSQLite 2.2.2 is about to hit CRAN. This package now fails checks, I'm having trouble to understand why.

I could relate the failures to r-dbi/RSQLite#338 -- if I revert this particular change (locally with `git revert -m 1 7f2a4c8`), the tests seem to pass.

The change in RSQLite introduces random savepoint names, and accesses the random number generator. Why would use of the RNG break the test?

Do you mind if I proceed with the RSQLite release and break your package on CRAN?

**Comment by eliotmcintire** [comment]
Thanks @krlmlr . I will try to look at this today.

**Comment by eliotmcintire** [comment]
Thanks again @krlmlr. By stating what your change is, it made it really easy to diagnose and fix. It only affects tests, not code. Go ahead, submit to CRAN.
