### ISSUE TITLE
remove 'copyFile'?

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#2]
`copyFile` is currently in `SpaDES` and `reproducible`. It should only be in one of these packages, and the code moved to a separate file (instead of keeping it in cache.R).

https://github.com/PredictiveEcology/reproducible/blob/master/R/cache.R#L1165-L1241

**Comment by achubaty** [comment]
I had begun fixing up `SpaDES::copyFile`, so that is the version we should use once.

**Comment by eliotmcintire** [comment]
Current `copyFile` is being used in a very precise way to deal with Caching of file-backed rasters, placing the file-backing inside the cache repository. I has been removed from `SpaDES`. Any modifications of `copyFile` should be a new issue.
