### ISSUE TITLE
add warning when system "unzip" is not set

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/reproducible#202]
This problem has bitten me again now that I'm using a new  achine where I don't have admin previledges.

When `preProcess` tries to extract a very large (>4Gb) file from a `.zip` archive it uses a `system2` call on `unzip`. However, _even with Rtools_ installed, this can happen:
```
Sys.which("unzip")
unzip 
   "" 
```
meaning that the `system`2 call will do nothing - with no error/warning whatsoever because `stdout = NULL`:
```
Browse[9]> system2("unzip", args = paste0(pathToFile, " -d ", 
+                                .tempPath), wait = TRUE, stdout = NULL)
```

```
If we allow stdout = TRUE then we get:
Browse[9]> system2("unzip", args = paste0(pathToFile, " -d ", 
+                                .tempPath), wait = TRUE, stdout = TRUE)
Error in system2("unzip", args = paste0(pathToFile, " -d ", .tempPath),  : 
  '"unzip"' not found
```

So I'd like to suggest that we either let `stdout = TRUE` or that we check that `unzip` can be found beforehand with `Sys.which("unzip")`. Suggestion:
```
      messagePrepInputs("File unzipping using R does not appear to have worked.", 
        " Trying a system call of unzip...", verbose = verbose)
        if (Sys.which("unzip") == "") {
        stop("unzip command cannot be found. Please try reinstalling Rtools and/or adding it to system path (see 'https://cran.r-project.org/bin/windows/Rtools/')"
        }
```

**Comment by eliotmcintire** [comment]
There were a few other cases that needed to be dealt with at the same time. I have taken the suggestion here, implemented part of it affdbd02011b9e2c1b651452d8834a67ebd3ad34 and it should be pulled in to @development soon.
