### ISSUE TITLE
add reproducible to CRAN 'ReproducibleResearch' task view

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#214]
Not sure exactly how to get added to <https://cran.r-project.org/web/views/ReproducibleResearch.html>, but presumably contacting the maintainer of that list/page whould do the trick

**Comment by achubaty** [comment]
Looks like we simply need to open a new issue here: https://github.com/jdblischak/reproducible-research-ctv/issues/new?template=package_suggestion.md

**Comment by eliotmcintire** [comment]
It is there in an not-perfect place... 
https://cran.r-project.org/web/views/ReproducibleResearch.html
