### ISSUE TITLE
fail with cropInputs and useSAcrs = FALSE

### ISSUE THREAD

**Issue by ianmseddy** [PredictiveEcology/reproducible#222]
on line 110 of test-prepInputs.R, the test is failing because `ymin` of x and `studyArea` are not identical. 
```
expect_true(isTRUE(all.equal(extent(shpEcozoneSm), extent(StudyArea))))
Error: isTRUE(all.equal(extent(shpEcozoneSm), extent(StudyArea))) is not TRUE
`actual`:   FALSE
`expected`: TRUE 
```
The error occurs during `cropInputs`, as the extent of `studyArea` is reprojected to the CRS of `x`, however this reprojection appears to be too small in the y-dimension.

**Comment by achubaty** [comment]
>The fail is because the ymin is not identical. I think it's ultimately because the two CRS are not the same (one is WGS84 ellipsoid, the other is GRS80). For some reason, compareCRS is not identifying this. I don't have a solution yet.
> ```r
> Browse[4]> crs(yyySF)
> CRS arguments: +proj=longlat +ellps=GRS80 +no_defs 
> Browse[4]> crs(studyArea)
> CRS arguments: +proj=longlat +datum=WGS84 +no_defs 
> Browse[4]> compareCRS(yyySF, studyArea)
> [1] TRUE
> ```
> Anyway, because the `x` polygon is first cropped to the extent of `studyArea`, it won't be equivalent when reprojected.
Dark blue is the `studyArea`, light blue is the extent used to crop `x`.

![image](https://user-images.githubusercontent.com/3435577/127072459-3d3b12c9-4950-4ea8-8282-2745753982ac.png)

> This error led me to this doc. It confirmed the ellipsoids are approximately the same, but the datums might be different. So it's possible the first crs (that of studyArea) has a completely different datum, like NAD83.  Though the ellipsoids are very similar, transforming the datums can introduce error that is "large relative to their difference". So that might explain what is occurring? But then I don't know why compareCRS wouldnt' pick up on that. I think I started looking into the sf tools for describing crs, and then I got distracted

[OverviewCoordinateReferenceSystems.pdf](https://github.com/PredictiveEcology/reproducible/files/6881701/OverviewCoordinateReferenceSystems.pdf)

**Comment by eliotmcintire** [comment]
No longer relevant
