### ISSUE TITLE
Weird file naming resulting in error when caching a postProcess call 

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/reproducible#227]
# REPREX
library("Require")
Require("reproducible")
Require("SpaDES.tools")
Require("raster")

rtm <- raster(ncol = 100, nrow = 100)
rtm[] <- sample(x = 1:20, size = ncell(rtm), replace = TRUE)
studyArea <- SpaDES.tools::randomPolygon(x = matrix(data = c(0,0), nrow = 1),
                                         area = 10^14)
### Create a temporary folder for the tests
tempDir <- tempdir()
on.exit(unlink(tempDir))
### Checking the raster
plot(rtm); plot(studyArea, add = TRUE, border = " red")
lay1 <- lay2 <- rtm
lay1[] <- rnorm(n = ncell(rtm))
lay2[] <- rnorm(n = ncell(rtm), mean = 5, sd = 0.5)
rtm <- projectInputs(rtm, targetCRS = "+init=epsg:4269 +proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")
stk <- stack(lay1, lay2)

#### To hit the naming bug, it seems to have to be a combination of reprojection happening, and lowmemory values
rasterOptions(maxmemory = 0.1)

#### If the stack and the RTM have different projections, we hit the bug because reprojecting saved the files to disk
maskedStk <- postProcess(x = stk, 
                         destinationPath = tempDir,
                         rasterToMatch = rtm, 
                         studyArea = studyArea,
                         filename2 = "nameOfTheLayer")
### Object exists, but with weird name
maskedStk[[1]]

#### With a Cached call, it errors because of the weird name; Cache can't create the FileBackedRaster

maskedStk <- Cache(postProcess, x = stk, 
                         destinationPath = tempDir,
                         rasterToMatch = rtm, 
                         studyArea = studyArea, 
                         filename2 = "nameOfTheLayer")

### If we pass the filename2 with the extension, the problem doesn't happen. But in either case, it seems that the stack was not reprojected
maskedStk <- Cache(postProcess, x = stk, 
                         destinationPath = tempDir,
                         rasterToMatch = rtm, 
                         studyArea = studyArea, 
                         filename2 = "nameOfTheLayer.grd")
maskedStk[[1]]

#### With my accompanying PR, the problem is solved and the reprojection actually happens although it seems to trigger some the function rasterize for the raster stack and errors, but it does not interrupt/errors the function.

**Comment by eliotmcintire** [comment]
It seems like there won't be a reprojection with these 2 projections: they are considered identical. I updated your PR with what I think are corrections. Just waiting for tests...
```
> compareCRS(maskedStk, stk)
[1] TRUE
> compareCRS(maskedStk, rtm)
[1] TRUE
> crs(rtm)
CRS arguments:
 +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs 
> crs(stk)
CRS arguments: +proj=longlat +datum=WGS84 +no_defs 
> crs(maskedStk)
CRS arguments:
 +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs
```

**Comment by eliotmcintire** [comment]
PR #228
