### ISSUE TITLE
Please attend to retirement of rgdal, rgeos and maptools

### ISSUE THREAD

**Issue by rsbivand** [PredictiveEcology/reproducible#253]
See: https://r-spatial.org/r/2022/04/12/evolution.html. **sp** on CRAN now offers control of the environment variable, so the attached log is from `_SP_EVOLUTION_STATUS_=2 _R_CHECK_FORCE_SUGGESTS_=FALSE R CMD check reproducible_1.2.8.tar.gz`:
[00check.log](https://github.com/PredictiveEcology/reproducible/files/9055733/00check.log)

**Comment by rsbivand** [comment]
There are a number of failures wiith current released GDAL/PROJ/GEOS, but these may come from the rapid changes in **terra** and **raster**, here:
```
> library(sf)
Linking to GEOS 3.11.0, GDAL 3.5.2, PROJ 9.1.0; sf_use_s2() is TRUE
> packageVersion("sf")
[1] '1.0.9'
> library(terra)
terra 1.6.18
> gdal(lib="all")
    gdal     proj     geos 
 "3.5.2"  "9.1.0" "3.11.0" 
> library(raster)
Loading required package: sp
> packageVersion("raster")
[1] '3.6.3'
```
These check outputs are for released **reproducible** and R-devel:
[test-all.Rout.zip](https://github.com/PredictiveEcology/reproducible/files/9663453/test-all.Rout.zip)
[00check.log](https://github.com/PredictiveEcology/reproducible/files/9663456/00check.log)
For  **reproducible** `development` branch:
[test-all.Rout.zip](https://github.com/PredictiveEcology/reproducible/files/9663513/test-all.Rout.zip)
[00check.log](https://github.com/PredictiveEcology/reproducible/files/9663527/00check.log)

**Comment by rsbivand** [comment]
This is a reprex with PROJ 8 (which exposes datum ensembles):
```
f <- system.file("ex/lux.shp", package="terra")
v <- terra::vect(f)
v <- v[1:2,]

rf <- system.file("ex/elev.tif", package="terra")
xOrig <- terra::rast(rf)
x <- xOrig
xCut <- terra::classify(xOrig, rcl = 5)
xVect <- terra::as.polygons(xCut)

tf1 <- tempfile(fileext = ".shp")
t11 <- reproducible::postProcessTerra(xVect, v, writeTo = tf1)
tw_t11 <- terra::wrap(t11)
vv <- terra::vect(tf1)
tw_vv <- terra::wrap(vv)

identical(tw_vv, tw_t11)
cat(tw_vv@crs, "\n")
cat(tw_t11@crs, "\n")
```
that is that `identical()` should not be expected when crossing a PROJ7/PROJ8 version border. `terra::gdal(lib="PROJ")` gives the PROJ version in the running **terra**.

**Comment by rsbivand** [comment]
Very possibly `tf1 <- tempfile(fileext = ".shp")` should use a different driver:
```
f <- system.file("ex/lux.shp", package="terra")
v <- terra::vect(f)
v <- v[1:2,]
cat(terra::crs(v), "\n")

rf <- system.file("ex/elev.tif", package="terra")
xOrig <- terra::rast(rf)
x <- xOrig
xCut <- terra::classify(xOrig, rcl = 5)
cat(terra::crs(xCut), "\n")
xVect <- terra::as.polygons(xCut)
cat(terra::crs(xVect), "\n")

tf1 <- tempfile(fileext = ".gpkg")
t11 <- reproducible::postProcessTerra(xVect, v, writeTo = tf1)
cat(terra::crs(t11), "\n")
tw_t11 <- terra::wrap(t11)
vv <- terra::vect(tf1)
cat(terra::crs(vv), "\n")
tw_vv <- terra::wrap(vv)

identical(tw_vv, tw_t11)
# [1] TRUE
cat(tw_vv@crs, "\n")
cat(tw_t11@crs, "\n")
```
This with the patches to **terra** in https://github.com/rspatial/terra/commit/b52909b454bdc8291529a9241c55175b0947f374

**Comment by rsbivand** [comment]
For **reproducible**, the problem is that `identical()` does not give special treatment to the `"crs"` objects, so:
```
> all.equal(tw_vv, tw_t11)
[1] "Attributes: < Component \"crs\": 1 string mismatch >"
```
which is more informative. The **sf** logical operator for the `"crs"` objects is better:
```
> sf::st_crs(tw_vv@crs) == sf::st_crs(tw_t11@crs)
[1] TRUE
```
A solution that works and takes account of the problem that `"ESRI Shapefile"` only supports `ESRI WKT1` is:
```
f <- system.file("ex/lux.shp", package="terra")
v <- terra::vect(f)
v <- v[1:2,]

rf <- system.file("ex/elev.tif", package="terra")
xOrig <- terra::rast(rf)
terra::crs(v) <- terra::crs(xOrig)
x <- xOrig
xCut <- terra::classify(xOrig, rcl = 5)
xVect <- terra::as.polygons(xCut)

tf1 <- tempfile(fileext = ".gpkg")
t11 <- reproducible::postProcessTerra(xVect, v, writeTo = tf1)
tw_t11 <- terra::wrap(t11)
vv <- terra::vect(tf1)
tw_vv <- terra::wrap(vv)

identical(tw_vv, tw_t11)
```
This imposes the PROJ > 7 definition on `v`, so agreeing with `xVect` and `xCut`, then uses `"GPKG"` not `"ESRI Shapefile"` to preserve the CRS in `reproducible::postProcessTerra()`.

**Comment by eliotmcintire** [comment]
Thank you. We will deal with this within next 2 weeks. We have had a backlog.

**Comment by rhijmans** [comment]
With "terra" and PROJ "8.2.1" I now see this error: 

```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-postProcessTerra.R:120'): testing terra ──────────────────────
  terra::wrap(vv) not identical to terra::wrap(t11).
  Attributes: < Component "crs": 1 string mismatch >
  
  [ FAIL 1 | WARN 1 | SKIP 67 | PASS 431 ]
``` 

I am assuming that this is for the reasons discussed above. Am I right?

**Comment by eliotmcintire** [comment]
All gone now

**Comment by rsbivand** [comment]
Thanks, just a single note when `rgdal` is not on the library path, see https://r-spatial.org/r/2023/04/10/evolution3.html:

[00check.log](https://github.com/PredictiveEcology/reproducible/files/11330721/00check.log)
