### ISSUE TITLE
move normPath() et al. tests to Require

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#261]
with https://github.com/PredictiveEcology/Require/issues/47

> aee6a6854f52a7810f63d0acada4b64147ffd70f will temporarily cause tests to fail until we can depend on the latest `Require@archivedPkg` where this issue was fixed (https://github.com/PredictiveEcology/Require/commit/dc640f94d2ca558a82665a1823a5debaedc3d233)

**Comment by eliotmcintire** [comment]
I removed `Require` from `reproducible` dependencies. So, these have to stay in both... unless we decide to include `Require`...
