### ISSUE TITLE
Cache "passthrough" fails in some cases

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#264]
`pemisc::MapOrDoCall()` would hanging indefinitely running the following with `useCache = FALSE` on R 4.2.1 Ubuntu 20.04:

```r
obj <- do.call(Cache, args = append(multiple, alist(Map2, fn,
                                                     MoreArgs = single,
                                                     cl = cl,
                                                     useCache = useCache)))
```

whereas explicitly doing the conditional version works fine:

```r
if (isTRUE(useCache)) {
  obj <- do.call(Cache, args = append(multiple, alist(Map2, fn, MoreArgs = single, cl = cl)))
} else {
  obj <- do.call(Map2, args = append(multiple, alist(fn, MoreArgs = single, cl = cl)))
}
```

The `fn` that caused hanging is `map::addColumnNameForLabels`, which doesn't actually do anything for a list of rasters (just returns the original objects), so there is nothing about that particular function that is problematic -- it looks to be a `Cache` issue.

Just for fun, I can't reproduce this simply -- I'm hitting it within LandWeb postprocessing code invoked from a SpaDES module, etc.

**Comment by eliotmcintire** [comment]
This is one of those cases where we need to get the user to reverse the do.call and Cache.  Now there is a clear error and reason and solution. The reason for this is there is ambiguity about which arguments need to be passed to which function. 
```
> do.call(Cache, args = append(list(rnorm), list(1, 2, 3)))
Error in .fnCleanup(FUN = FUN, callingFun = "Cache", ..., .functionName = .functionName, :
It looks like Cache is called incorrectly, possibly something like do.call(Cache, args);
Cache should be the outermost function. See examples for correct ways to use Cache

# Should, instead be this:
Cache(do.call(rnorm, args = list(1, 2, 3)))
# or
Cache(do.call, rnorm, args = list(1, 2, 3))
# or perhaps most clearly:
do.call(rnorm, args = list(1, 2, 3)) |> Cache()
```

I am not sure if this will solve the issue identified here. The other package will have to deal with this if it is still failing.
