### ISSUE TITLE
Cache not working with `terra::SpatRaster` objects representing NetCDF files with multiple variables

### ISSUE THREAD

**Issue by nbsmokee** [PredictiveEcology/reproducible#296]
I think this has not been reported before. If it has, sorry for spamming.

I have `terra::SpatRaster` object representing a data set with multiple variables, and want to cache the output of some function operating on only a single one of them. This works just fine if the source of said SpatRaster object is memory, but fails if the object is referencing a NetCDF file. Here is a MWE showcasing the described behavior:

``` R
library(terra)
library(reproducible)

# memory
raster <- reproducible::prepInputs(
  targetFile = "ECMWF_ERA-40_subset.nc",
  url = "https://www.unidata.ucar.edu/software/netcdf/examples/ECMWF_ERA-40_subset.nc",
  fun = "terra::rast"
)
reproducible::Cache(sum, raster$tcw_1)
# works just fine

# disk
raster2 <- terra::rast("ECMWF_ERA-40_subset.nc")
reproducible::Cache(sum, raster2$tcw_1)
# Error: The file does not exist: NETCDF:"<path-to-project-dircetory>/ECMWF_ERA-40_subset.nc":tcw
```
Cheers :beers:

**Comment by eliotmcintire** [comment]
Thank you. This will be a helpful reprex for the next release of `reproducible`.

**Comment by nbsmokee** [comment]
I just rerun the test case above and noticed an error so to say in my MWE. It seems like running the first section
``` R
raster <- reproducible::prepInputs(
  targetFile = "ECMWF_ERA-40_subset.nc",
  url = "https://www.unidata.ucar.edu/software/netcdf/examples/ECMWF_ERA-40_subset.nc",
  fun = "terra::rast"
)
reproducible::Cache(sum, raster$tcw_1)
```
for the first time in a fresh R environment does indeed NOT work just file, but instead produces the same error as the second section. When running for a second time, it worked as described though.

**Comment by eliotmcintire** [comment]
@nbsmokee. I see your fix strips a prefix and suffix. Will NETCDF files always have that prefix and suffix in the filename with `terra::sources`? I ask because we may want to be a bit smarter about removing it, i.e., can we `if (grepl("^NETCDF", x))` prior to removing, so that we can only affect this class of object.

```
Browse[2]> terra::sources(object)
[1] "NETCDF:\"C:/Eliot/GitHub/reproducible/ECMWF_ERA-40_subset.nc\":tcw"
```

**Comment by nbsmokee** [comment]
I think this format comes from GDAL, which is what terra uses under the hood. In the GDAL documentation section about the NetCDF driver (https://gdal.org/drivers/raster/netcdf.html) it says:
> The name of individual images are assigned to the SUBDATASET_n_NAME metadata item. The description for each image is found in the SUBDATASET_n_DESC metadata item. For NetCDF images will follow this format: 
NETCDF:filename:variable_name

So yes, I think the prefix will always be "NETCDF". I tested this with some NetCDF files from a different source, and the behavior is the same as in my MWE.

**Comment by nbsmokee** [comment]
I opened a new pull request (I messed up the former one by accidentally pushing another commit to my master) where I already incorporated the smarter solution using `grepl("^NETCDF:", x)`. For me it seems to work so far.
