### ISSUE TITLE
move 'SpaDES::checkPath' here?

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#3]
`checkPath2` is more-or-less a copy of `SpaDES::checkPath`. If it's needed here, then we should move the original (and its friends) out of `SpaDES` and into this package.

**Comment by eliotmcintire** [comment]
I am not sure about this.  Are `checkPath` and `normPath` part of a "reproducible" work flow?  Maybe the answer is yes.

**Comment by achubaty** [comment]
Yes, in part because they standardize paths (*e.g.*, across OSes) more consistently than the standard R tools these wrap around.

**Comment by eliotmcintire** [comment]
Ok. I am proceeding with these two functions into reproducible

**Comment by eliotmcintire** [comment]
Done with e4256cc76805abcba9e9836c6694c3ea827fa9d1
