### ISSUE TITLE
archives with nested folder structure and identical base filenames

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#307]
related to #181 and #224, the following example would fail by extracting identically named files from subdirs of the archive, overwriting eachother.

this may already be dealt with but here's a quick reprex using climate data from ClimateNA.

```r
library(googledrive)
library(reproducible)

climateDataURL <- "https://drive.google.com/file/d/1we9GqEVAORWLbHi3it66VnCcvLu85QIk"
inputPath <- checkPath(file.path(tempdir(), "inputs"), create = TRUE)

## extracts flat files, overwriting and keeping only the last subdir's files
res2 <- preProcess(url = climateDataURL, destinationPath = inputPath)
res2
```

**Comment by eliotmcintire** [comment]
Reprex worked well. Thank you.

All passing now in feature branch. Will merge in `development` shortly.
