### ISSUE TITLE
prepInputs is deleting file's CRS

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/reproducible#31]
prepInputs is deleting raster's crs likely at preProcess stage.
This is happening in development branch and when using prepInputs inside and outside of a module. Reproducible example in the link: https://github.com/tati-micheletti/testModule/blob/master/global.R

**Comment by eliotmcintire** [comment]
This, I believe, is resolved with series of commits: 6901ca861ce159edc088c34c371d615ff363ebe9
