### ISSUE TITLE
use testthat test fixtures for test setup and teardown

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#311]
ensure temp files, options, and other testing pieces work consistently and can be run interactively

see <https://testthat.r-lib.org/articles/test-fixtures.html>

**Comment by eliotmcintire** [comment]
`reproducible` already has equivalent functionality with `testInit`. This is a nice to have, but I am closing this as too low priority. We can re-open if some day we feel it gets back on the todo list.
