### ISSUE TITLE
test failure using data.table from github master

### ISSUE THREAD

**Issue by tdhock** [PredictiveEcology/reproducible#314]
Hi @eliotmcintire 
After installing data.table from github master,
```r
data.table::update_dev_pkg()
```
And then running R CMD check on reproducible, I get the following new failure, (which is not present if you use data.table from CRAN)
```
* checking tests ...
  Running 'test-all.R'
 ERROR
Running the tests in 'tests/test-all.R' failed.
Last 13 lines of output:
  length(out) not identical to 2L.
  1/1 mismatches
  [1] 3 - 2 == 1
  -- Failure ('test-misc.R:288:3'): test miscellaneous fns -----------------------
  length(out) not identical to 1L.
  1/1 mismatches
  [1] 2 - 1 == 1
  -- Failure ('test-misc.R:295:3'): test miscellaneous fns -----------------------
  length(out) not identical to 2L.
  1/1 mismatches
  [1] 3 - 2 == 1
  
  [ FAIL 3 | WARN 3 | SKIP 85 | PASS 421 ]
  Error: Test failures
  Execution halted
```
data.table needs to ensure that updates do not break dependent packages like reproducible, before uploading new versions to CRAN, so can you please submit an updated version of reproducible to CRAN, that fixes this test failure? In particular, I would suggest to avoid testing the printed output from data.table, and instead test the data values.

**Comment by eliotmcintire** [comment]
Will do asap

**Comment by eliotmcintire** [comment]
Closes #314. Changes that pass these fails are now pushed to `development` branch. This branch is scheduled to be submitted to CRAN in about 7 days.

These tests are actually about testing a `messageDF` function that prints a data.frame/data.table in a clean way using `message`, so the test requires `capture.output` to ensure the messaging is correct.

Thank you for the work on `data.table` :)

**Comment by eliotmcintire** [comment]
I have changed it to just use the `options(datatable.print.class = FALSE)`. This is a simple update and tests pass still with original code.

**Comment by tdhock** [comment]
great, thanks! I confirm there is no longer any issue, using the current version of reproducible from CRAN.
