### ISSUE TITLE
Rasters made with prepInputs diverge on resolution from others not created with it

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/reproducible#33]
When I create all my rasters with prepInputs, all rasters'  resolutions are up scaled to 4000x4000m. However, if one of my rasters is not downloaded/read using prepInputs, it keeps its original resolution and there are some operations I just can't run on them because of this difference in resolution. I used to think that this "SmallRaster.tif" file create would just somehow point to the original raster with original size (the one it would actually use for the operations), but it doesn't seem to be the case as I had error such as the one described. What am I missing?

**Comment by achubaty** [comment]
What template are you using for the cropping/reprojecting, etc? Are you specifying the resolution in your call to `prepInputs`?

Please note that questions about usage etc. should be directed to the [SpaDES user group](https://groups.google.com/d/forum/spades-users). This issue tracker is for reporting bugs.
