### ISSUE TITLE
`postProcess`/`postProcessTo` fail when `to` and `projectTo` are supplied

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/reproducible#331]
From the documentation of `postProcessTo`, I understood that we can pass `projectTo` to override `to` when projecting, but there seems to be something wrong with the extent  (even when passing a `crs` object)

```
Require::Require(c("terra", 
                   "PredictiveEcology/reproducible@development (HEAD)"))

ext2 <- terra::ext(c(xmin = -3229772.32501426,
                     xmax = 3680227.67498574,
                     ymin = -365833.605586135,
                     ymax = 3454166.39441387))
x <- terra::rast(ext2,
                 crs = paste("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0",
                             "+a=6370997 +b=6370997 +units=m +no_defs"),
                 res = c(10000, 10000))
x <- terra::setValues(x, 1)

RTMext <- terra::ext(c(
  xmin = -1613500.00000023,
  xmax = -882500.000000228,
  ymin = 7904500,
  ymax = 9236000))
RTM <- terra::rast(RTMext,
                   crs = paste("+proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95 +x_0=0 +y_0=0",
                               "+ellps=GRS80 +units=m +no_defs"),
                   res = c(250, 250))
RTM <- setValues(RTM, 2)
RTM[sample(1:ncell(RTM), 5000)] <- NA
SA <- as.polygons(RTM)

out <- postProcess(x = x, to = RTM, projectTo = SA, filename2 = NULL)
out2 <- postProcess(x = x, to = RTM, projectTo = crs(SA), filename2 = NULL)

## same problem:
out3 <- postProcessTo(from = x, to = RTM, projectTo = crs(SA), filename2 = NULL)
```

**Comment by eliotmcintire** [comment]
It looks like they don't overlap...

![image](https://github.com/PredictiveEcology/reproducible/assets/1100507/88658afd-001b-464a-a546-66545b028ac1)

**Comment by CeresBarros** [comment]
In my example "what the user would want" is
- to use `to` as the source of information for extent (in place of `cropTo`), resolution (in place of `projectTo`, when it's a raster) and masking (in place of `maskTo`)
- to use `projectTo` as the source of  information for CRS only, given that it's supplied as a polygon (first case) or a CRS object (second case), neither of which have resolution information.

I think that the previous versions of `postProcess` used to be able to deal with this (but perhaps I'm wrong?) -- we think wewere ble to do it by passing a `rasterToMatch` on which extent/res/masking (with `maskWithRTM = TRUE`) would be based, but then use a `studyArea` for CRS only (with `useSAcrs = TRUE`). That's probably why I thought we could achieve this with the new version.
But I agree it may be hard to guess what the user wants. I would say that if the `projectTo` argument does _not_ have resolution information, then they just want CRS and, presumably, the subsequent masking would need to be done either before projecting OR with a re-projected `maskTo` object that matches the final CRS.

So, bottomline for me is: we don't need to "guess" anything or do the code gymnastics I just mentioned if the right way is to supply a template raster; but we do need to write the documentation to reflect this more clearly, perhaps.

**Comment by eliotmcintire** [comment]
I don't think previous versions would have been able to do this... in this case, the example is requesting to mask without alignment. This was always a problem... thus, one should use a raster template when doing a `project` on a raster.

For documentation... it is "doing" what it says, it just can't complete the mask. I will look at documentation about this and see if it can any clearer -- i.e., send the user to `?terra::project` to see the importance of passing a raster template for `project`
