### ISSUE TITLE
partial argument match of 'file' to 'fileFormat'

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#371]
outstanding from #366, calls to `Cache(saveRDS, ...)` in `test-Cache.R` that pass `file` are triggering this, I think, accidentally, because `file` is in the `...` of the Cache call and should be passed to `saveRDS` but are also being passed as `fileFormat` in `.getFromRepo()` calls

**Comment by eliotmcintire** [comment]
I believe this is fixed in @development
