### ISSUE TITLE
cache warnings: Don't need to call dbFetch() for statements, only for queries

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#5]
running `testthat::test("~/GitHub/reproducible", "cache)` generates a bajillion warnings:

```r
Don't need to call dbFetch() for statements, only for queries
```

This is likely new with the release of the latest `RSQLite` package, and cropping up in `archivist`, as I don't see any calls we make to `dbFetch()`. @eliotmcintire can you please confirm and file bug with `archivist` as needed?

I will temporarily add `suppressWarnings` to the tests.

**Comment by eliotmcintire** [comment]
Contacted `archivist` folks and they have fixed it. It will appear in CRAN eventually. pbiecek/archivist#316

**Comment by achubaty** [comment]
awesome, thanks!
