### ISSUE TITLE
caching of raster operations using different raster file types doesn't copy auxiliary files

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#53]
from @CeresBarros 

> following the crop, Cache tried to copy the raster to the cache/rasters folder. because this is a `.dat` file, it needs the accessory file `.hdr` - without it it wont load again

This should be an easy fix -- just need to make sure `Cache` is also coping the auxiliary `.hdr` file.

We should also check that other raster file types are also covered.

NOTE: this became an issue when working with large rasters that did not fit in RAM.

**Comment by eliotmcintire** [comment]
No longer relevant
