### ISSUE TITLE
internal messages (e.g., in prepInputs) not being printed

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/reproducible#75]
I noticed that the messages informing the user when file links or copies are being produced are not being printed when `linkOrCopy` is called internally from `prepInputs`.

**Comment by achubaty** [comment]
This is a more general problem with internal messages not being passed through in `prepInputs`. I previously reported this but I can't seem to find the issue at the moment.

**Comment by CeresBarros** [comment]
I think I know what's going on.... I'll update on my progress soon

**Comment by achubaty** [comment]
here is the related issue: https://github.com/eliotmcintire/LandWeb/issues/29

**Comment by CeresBarros** [comment]
@achubaty did you notice this issue with other functions, or just `linkOrCopy`?

**Comment by CeresBarros** [comment]
I solved the issue in `linkOrCopy` will PR ASAP

**Comment by achubaty** [comment]
per link above, I see it in `postProcess`

**Comment by achubaty** [comment]
i'd like to keep this open until it's 1) resolved for your case, and 2) resolved more generally (`postProcess`, `prepInputs`, etc.)

**Comment by eliotmcintire** [comment]
No longer relevant
