### ISSUE TITLE
Prepinputs: targetCRS matched by multiple actual arguments

### ISSUE THREAD

**Issue by ianmseddy** [PredictiveEcology/reproducible#77]
```
set.seed(1234)
polyMatrix <- matrix(c(-79.4712, 48.3935), ncol = 2)
areaSize <- 1000000
rP <- SpaDES.tools::randomPolygon(x = polyMatrix, hectares = areaSize)
#Put LCC2005  in the destinationPath directory

LCC05 <- reproducible::prepInputs(targetFile = "LCC2005_V1_4a.tif",
               destinationPath = "C:/Ian/temp",
               studyArea = randomPolygon,
               targetCRS = "+proj=lcc +lat_1=49 +lat_2=77 +lat_0=49 +lon_0=-95 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0")

Error in match.call(definition, call, expand.dots, envir) : 
formal argument "targetCRS" matched by multiple actual arguments. I'm guessing because postProcess tries to retrieve targetCRS from studyArea
```
Only occurs if studyArea and targetCRS are both included.

**Comment by ianmseddy** [comment]
So looking into this, maybe targetCRS was never intended to be something the user could specify. Rather it is sourced from RTM, SA, or is null. Not sure if this is an issue as much as a wishlist.

**Comment by eliotmcintire** [comment]
What is the behaviour you want?  You can pass the CRS with the studyArea (using `"useSAcrs = TRUE"`). Does that work? For rasters, which is what you have, it is safer to provide the rasterToMatch because that way you specify more than just the CRS e.g., resolution, origin, extent & crs, which are all needed.

**Comment by ianmseddy** [comment]
I think that is probably best to leave as is, and the user can just reproject the study Area or rtm. I think Tati wanted to avoid reprojecting a giant rasterTomatch, but didn't have a shapefile on hand. But that isn't really a prepInputs problem as much as a big data problem.
