### ISSUE TITLE
sideEffects

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/reproducible#8]
@MelinaHoule I haven't verified, but I believe that `sideEffect` argument is writing absolute paths, rather than relative paths. This means that the cache is not transferable to a different computer. 

Is it possible to make the paths relative instead of absolute?

**Comment by achubaty** [comment]
was this resolved?

**Comment by achubaty** [comment]
bump @eliotmcintire

**Comment by eliotmcintire** [comment]
This is not relevant any more
