### ISSUE TITLE
feature request: extract files to where the archive lives, not to top level of 'reproducible.inputPaths'

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#81]
When setting a `reproducible.inputPaths` directory that contains subdirectories with data, any files extracted from .zip/.tar.gz archives get extracted to top level instead of within the subdirectory of their origin. It makes a mess of my otherwise organized data directory!

`prepInputs()` and friends should extract these files into the basedir of the archive from which they were extracted.

**Comment by eliotmcintire** [comment]
This is not the purpose of `inputPaths`. It is strictly a cache directory. It is not for organising files.
