### ISSUE TITLE
Pipe for use with Cache

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/reproducible#9]
Caching would be very nice if it worked with a pipe. Looking at source code of `magrittr::%>%`, it is clear that the pipe would not work in this case because each step is evaluated in sequence. The objective of caching is to examine the arguments, *without evaluating them*, then determine whether this has been called before. If yes, then pull return value from the cached copy. 

I have put together a version of the pipe operator that is identical to the `magrittr::%>%`, but the addition of a new section of code to determine if there is a `Cache` call in the pipe sequence. If yes, then it will call Cache internally on all unevaluated elements of the whole pipe sequence. If it has already been done, then returns final return. If not, then the whole pipe sequence is evaluated within the `Cache` call, giving it the normal Cache attributes.

These changes made in feature branch: 493a0472b428d4ce99c9dc41cbca67c24f418286

Obvious drawback is overwriting the magrittr pipe *and* it requires using unexported functions from `magrittr`, via `getFromNamespace`, which may not pass CRAN.

@achubaty Thoughts?

```
devtools::install_github("PredictiveEcology/reproducible@PipeForCache")
tmpdir <- file.path(tempdir(), "testCache")
checkPath(tmpdir, create = TRUE)
a <- rnorm(10, 16) %>% mean() %>% prod(., 6)
b <- rnorm(10, 16) %>% mean() %>% prod(., 6) %>% Cache(cacheRepo = tmpdir)
d <- rnorm(10, 16) %>% mean() %>% prod(., 6) %>% Cache(cacheRepo = tmpdir)
all.equal(b,d)
all.equal(a,d) # FALSE because a is a random number, d is from a Cached call
unlink(tmpdir, recursive = TRUE)
```

**Comment by achubaty** [comment]
this is a great idea. is there a way we can get this without using + modifying `magrittr` code? (maintaining this as changes are made to `magrittr` will be a pain. I don't suppose we can provide a wrapper?)

**Comment by eliotmcintire** [comment]
Because, at the core, it is a sequential evaluation, I can't see a way to wrap it or somehow provide a pre-modifier.

Looking at the pipe source code, it hasn't changed in 3 years https://github.com/tidyverse/magrittr/commits/master/R/pipe.R ... last commit with code change was: 4e9215a092e51a3fcdbf16bd56f6f22bdf85c511, so, we may be ok.

**Comment by achubaty** [comment]
related https://github.com/tidyverse/magrittr/issues/148

is the intent to cache the entire pipeline, or simply some of the steps? inexpensive intermediate steps don't really need to be cached, and it'd be nice to have more control over what gets cached:

```r
## cache the last step
rnorm(10, 16) %>% mean() %>% prod(., 6) %>% Cache(cacheRepo = tmpdir)

## cache an intermediate step only
rnorm(10, 16) %>% Cache(cacheRepo = tmpdir) %>% mean() %>% prod(., 6)
```

**Comment by eliotmcintire** [comment]
Already done. See examples. aba6ac93cae11837a2174b77e14a0948e71f7aac

**Comment by eliotmcintire** [comment]
It won't work to have >1 Cache call in a pipe, however.

**Comment by achubaty** [comment]
see also https://github.com/tidyverse/magrittr/issues/120

**Comment by achubaty** [comment]
and https://github.com/tidyverse/magrittr/issues/43

**Comment by eliotmcintire** [comment]
I think this Caching of the pipe sequence is similar, but not identical to the linked discussions above.

1. We still want and will do sequential evaluation (the first time through the pipe chain).
2. The second time through it will act *as if* it were doing sequential evaluation, but essentially jump to the last step.

So, this is not the same as creating a lazy evaluation AND we still want it to be eager evaluation the first time. 

It is similar because it is intercepting the whole pipe (up to the Cache) to determine whether or not it has  previously done the pipe in the exact sequence.

**Comment by achubaty** [comment]
Cache pipe previously implemented. @eliotmcintire can this issue be closed?

**Comment by eliotmcintire** [comment]
This is now its own pipe ...  `Cache()` ... `%C%` ... cache pipe. We had redefined the regular pipe for 1 year, and it was not obvious what the behaviour should be. Closing this. `?%C%`
