### ISSUE TITLE
Improve the edge cases for prepInputs for files of unknown type

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/reproducible#95]
From @achubaty 

> Rather than relying on file extension, we should try to get the file type (e.g., the way to do this on linux is using file). see https://stackoverflow.com/questions/33797558/determine-file-type-in-r-based-on-the-content.

> I'm not sure how this works on Windows (see daqana/dqmagic#4 (comment)).

**Comment by tati-micheletti** [comment]
I'm on it.

**Comment by tati-micheletti** [comment]
I think this is solved, we should close the issue. @eliotmcintire

**Comment by eliotmcintire** [comment]
Seems like `dqmagic` for Windows is still experimental. Closing this as the specific issue is experimentally resolved here.
