### ISSUE TITLE
cloudCache: move writing and upload of cache object to child process

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#97]
caching large objects blocks the main R process for a long time as the object is written to disk and uploaded.

we should try to move this to a child process, perhaps using `future`.

**Comment by eliotmcintire** [comment]
I already tied it on windows, and it was extremely inefficient. Focus primarily on Linux types for now.

**Comment by eliotmcintire** [comment]
implemented on Linux 992e6b45ccc534550ac31e5154cad276d7b1c4df
